//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCcourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class inform
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public inform()
        {
            this.shops = new HashSet<shop>();
        }
    
        public int i_id { get; set; }
        public string message { get; set; }
        public Nullable<System.DateTime> datatime { get; set; }
        public string place { get; set; }
        public Nullable<int> in_id { get; set; }
    
        public virtual teacher teacher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<shop> shops { get; set; }
    }
}
