//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCcourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class shop
    {
        public int shop_id { get; set; }
        public Nullable<int> s_id { get; set; }
        public Nullable<int> i_id { get; set; }
        public Nullable<int> t_id { get; set; }
    
        public virtual inform inform { get; set; }
        public virtual student student { get; set; }
        public virtual teacher teacher { get; set; }
    }
}
