//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCcourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Viewt_class_college
    {
        public int c_id { get; set; }
        public string collegeName { get; set; }
        public int cs_id { get; set; }
        public string grade { get; set; }
        public string classNum { get; set; }
        public Nullable<int> cl_id { get; set; }
    }
}
