//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace myCcourse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_teacer_Type
    {
        public int t_id { get; set; }
        public string t_name { get; set; }
        public string t_password { get; set; }
        public Nullable<int> t_age { get; set; }
        public Nullable<int> teachingAge { get; set; }
        public string sex { get; set; }
        public string t_Phone { get; set; }
        public string t_Email { get; set; }
        public Nullable<int> t_type { get; set; }
        public int tt_id { get; set; }
        public string type { get; set; }
    }
}
